services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: ./data/postgres
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"




volumes:
    postgres:

