spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    password: postgres
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update